### ISSUE TITLE
Question: behaviour of tsserver with editing new TS files (files that don't exist in disk yet) 

### ISSUE THREAD

**Issue by ajitid** [williamboman/nvim-config#2]
I've noticed that if I use pyright for Python and use `:e main.py`, pyright attaches itself to the file but if I do the same for a TypeScript file using tsserver with `:e app.ts`, tsserver doesn't attaches itself. I have to save the file then run `:e` so that tsserver client can then attach to the buffer. Have you faced this issue on your machine? I've tried this on my another machine and still can reproduce it.

**Comment by ajitid** [comment]
Okay, seems like tsserver needs a file on the disk and it just can't work without it, so this scenario cannot be handled with tsserver. Closing this.

**Comment by zlksnk** [comment]
So If I run `:LspStart` on a TS file without first saving it, it gives me this issue:

```
Autostart for eslintls failed: matching root directory not detected.
Autostart for tsserver failed: matching root directory not detected.
```

Can this be somehow fixed? (By this I mean can this be matched to pyright behaviour?)

**Comment by ajitid** [comment]
So If I run `:LspStart` on a TS file without first saving it, it gives me this issue:

```
Autostart for eslintls failed: matching root directory not detected.
Autostart for tsserver failed: matching root directory not detected.
```

Can this be somehow fixed? (By this I mean can this be matched to pyright behaviour?)

**Comment by ajitid** [comment]
Fixed by https://github.com/williamboman/nvim-lsp-installer/commit/c0ca69cfbd017d2ec4209278a0b74270f8dbdc18

**Comment by williamboman** [comment]
:+1:
